### PR TITLE
Updated cmake for linux

### PR DESCRIPTION
**Pull request by bbeck13**
You needs to define GLEW_DIR and GLFW_DIR in order for this to work (on gnu+linux)
https://github.com/bbeck13/RhythmRunner/issues/16

### CODE REVIEW

**Comment by josepharhar** [comment]
Are the submodules we are using for GLEW and GLFW not working on linux? Is that the whole problem?

**Comment by bbeck13** [comment]
Yea windows and mac have system level graphics headers that make it possible to use these libraries statically but that's not the case with gnu+linux, the libraries need to be installed onto the system since there are no default graphics headers

**Comment by josepharhar** [comment]
I'd like to see extra files/submodules for linux included in the source in the future, but this is good for now.
CR :fire: QA :100: on windows

**Comment by alexottoboni** [comment]
QA 👍 still works on my mac. I can try again on my Ubuntu desktop eventually when It decides to boot again...

**Pull request merged**
