### PR TITLE
Added debug definitions to cmake

### PR DESCRIPTION
**Pull request by bbeck13**
`make debug` makes the project with debug symbols for lldb, gdb, etc..
`make` makes the project and prints out our debug code to the console
`make release` makes the project in release mode no debug info

Let me know if this works for you. Try the make debug on windows I have no idea if it works.

### CODE REVIEW

**Comment by alexottoboni** [comment]
Can you add the `brew install` thing to the readme to get debug to work?

**Comment by alexottoboni** [comment]
Are you opposed to me adding another make target that skips compiling sfml?

**Comment by bbeck13** [comment]
`brew install lcov`
and go for it add it to this pr

**Comment by bbeck13** [comment]
fixed `default` target

**Comment by alexottoboni** [comment]
CR 🔢

**Pull request merged**
