### PR TITLE
Change All Groups of Spaces to Tabs

### PR DESCRIPTION
**Pull request by avilanicolas**
It is well known that \t is a single character while \s\s is two. By replacing all spaces of one or more, I have saved this project literal bytes of space. Bytes! That's a lot of bytes folks!

pls merge this in for me

### CODE REVIEW

**Comment by bbeck13** [comment]
As much as I love this I'd prefer it you changed every single space to a tab character. So that I have more separation between words when I am reading

**Comment by josepharhar** [comment]
https://raw.githubusercontent.com/calebhskim/grade-cstaley/master/sounds/Uh%2C%20No.wav

**Comment by Matthew-Stewart** [comment]
We would also need to add a new line between every existing line for better readability

**Comment by avilanicolas** [comment]
Great comment Matt! Will do. You too braden.

**Comment by avilanicolas** [comment]
give me a ship it and I will push to prod

**Comment by alexottoboni** [comment]
So this is a joke right...?

**Comment by avilanicolas** [comment]
no of cource not i put a lot of work into this writing that sed command to use

does it look like a joke? sorry cpp isn't my first language

**Pull request closed without merging**
