### PR TITLE
Added endgame screen

### PR DESCRIPTION
**Pull request by josepharhar**
This also adds a new way to detect if a key went from an unpressed state to a pressed state to help with @Matthew-Stewart 's doublejump changes: InputBindings::KeyNewlyPressed()

#47

### CODE REVIEW

**Comment by bbeck13** [comment]
This isn't working well for me pressing keys at the menu doesn't always work I'll try to investigate this. Please refactor this for matts changes to master. I like most of the changes though, the KeyNewlyPressed method is nice
screen shot 2017-02-16 at 10 23 28 am
This is on quit

**Comment by josepharhar** [comment]
@bbeck13 Yeah im working on it, Ill post another comment when I get something worth testing

**Comment by josepharhar** [comment]
@bbeck13 Try it now

**Comment by bbeck13** [comment]
CR 👍 QA 👍 looks good I'm still getting an error on exit but I think that's a separate issue

**Pull request merged**
