### PR TITLE
Matt.camera.rotate

### PR DESCRIPTION
**Pull request by Matthew-Stewart**
Hopefully my rebase didn't screw things up too badly

Use WASD to rotate camera around the player

### CODE REVIEW

**Comment by bbeck13** [comment]
I like the idea here but the camera get funky when the player moves in the Y dir it might be better to have the camera fixed above the player and only let the user move around in a circle above the player, giving the player control of all 4 axis's is a bit too much

**Comment by alexottoboni** [comment]
I rotated the camera around and died a few times and now it is out of sync so I can't see the bike anymore.

**Comment by Matthew-Stewart** [comment]
@alexottoboni thought i fixed that 😿  Ill see if i can debug it more

**Comment by bbeck13** [comment]
CR 👍 QA 👂

**Comment by bbeck13** [comment]
Don't merge yet! MERGE NOW

**Pull request merged**
