### PR TITLE
added define for asset dir

### PR DESCRIPTION
**Pull request by bbeck13**
let me know if I missed any definitions and if this works with your build

### CODE REVIEW

**Comment by anguy134** [comment]
hmm... Xcode is able to run and generate the level, but it fails to open .obj files. (doesn't render the bunny and platform). It can open the .wav file and does play music.

**Comment by bbeck13** [comment]
Try now

**Comment by anguy134** [comment]
Looks good now!

**Review by josepharhar — APPROVED** [review]
CR :100: QA :eyes:

**Pull request merged**
